### ISSUE TITLE
一些前端顯示問題

### ISSUE THREAD

**Issue by littleCube2019** [hi-i-m-GTooth/web-front_end_of_graduation_topic#8]
~1.  娛樂值普遍偏低
可能一樣要量化成五個部分，因為資料小數很小很小~

~2. 為了簡化前端，可以修改json檔
比如 geng 、 wordCloud 或許可以不用 [ ]包一層~

**Comment by hi-i-m-GTooth** [comment]
第二點有範例嗎？

**Comment by hi-i-m-GTooth** [comment]
> 1. 娛樂值普遍偏低
>    可能一樣要量化成五個部分，因為資料小數很小很小
> 2. 為了簡化前端，可以修改json檔
>    比如 geng 、 wordCloud 或許可以不用 [ ]包一層

第二點有範例嗎？

**Comment by littleCube2019** [comment]
目前是 [{key1: value1},{key2: value2},{key3: value3} ...]
要取用時 要寫
for obj in [{key1: value1},{key2: value2},{key3: value3} ...]:
        for (key,value) in obj:

改成 {key1:value1,key2:value2,key3:value3...}
只需要
 for (key,value) in {key1:value1,key2:value2,key3:value3...} 


不過  目前前端正常運作，也可以選擇不要再動他XD，這問題優先權可以放最低

**Comment by hi-i-m-GTooth** [comment]
第一點娛樂值有考慮正規化之類的嗎？這樣Progress bar也會好表現些～ (淺見：例如整個Corpus最大的娛樂值當分母之類的～)

**Comment by littleCube2019** [comment]
我想娛樂值就是ordinal scale的data，只在乎大小，其差距沒有太大意義
所以可以試試看

更新:
目前目測沒問題，待湛元更新完json檔後可以close issue (雲端已更新完畢)
另，人氣值可能考慮不夠多，相較娛樂值蠻多影片為0，可能要再觀察
